#!/usr/bin/env bash

# Update and perform some minor checks
echo -e "Updating and doing some minor checks...\n"

# Function to install a package if it's not already installed
function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup the default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the HAProxy configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 6111-web-01 54.221.170.202:80 check
    server 6111-web-02 54.208.135.69:80 check
"

# Update the HAProxy configuration file
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "Configured - Roundrobin On web-01 & web-02"

# Start or restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

# Print the required output
echo -e "[\"web-01\", \"web-02\"]"
